### ISSUE TITLE
brcm-bt-firmware fails due to mnt-conf not existing anymore

### ISSUE THREAD

**Issue by pcarranzav** [resin-os/resin-artik710#52]
In https://github.com/resin-os/resin-artik710/blob/master/layers/meta-resin-artik710/recipes-bsp/brcm-bluetooth/files/brcm-bt-firmware.conf - I tried replacing this for mnt-boot and it seemed to work, but I'm not sure if it's the right replacement.

**Comment by agherzan** [comment]
@floion can you please confirm this is fixed now? Is there anything else left to do?

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-artik710/pull/53
